name: chery_master_launcher
description: Ultimate Android Auto-like Launcher for Chery Vehicles (API 29)
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^17.1.0
  shared_preferences: ^2.5.4
  json_annotation: ^4.11.0
  permission_handler: ^12.0.1
  location: ^8.0.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  audioplayers: ^6.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

dev_dependencies:
  build_runner: ^2.11.1
  json_serializable: ^6.13.0
